const STORAGE_KEY = "cup-sleeve-archive-v2";
const FAVORITES_KEY = "cup-sleeve-favorites-v2";
const FRAME_KEY = "cup-sleeve-frame-v1";

function buildFrameTemplate() { const W = 4; const H = 3; const cx = W / 2; const cy = H + 3.2; const thickness = 0.55; const radiusStart = cy - H; const radiusMax = Math.hypot(W / 2, cy); const rows = Math.round((radiusMax - radiusStart) / thickness); const tileWidth = thickness * 1.95; const tiles = []; for (let row = 0; row < rows; row++) { const radius = radiusStart + thickness * (row + 0.5); const half = Math.asin(Math.min(1, W / 2 / radius)); const count = Math.max(2, Math.round((2 * half * radius) / tileWidth)); for (let index = 0; index < count; index++) { const alpha = -half + (2 * half * (index + 0.5)) / count; const centerX = cx + radius * Math.sin(alpha); const centerY = cy - radius * Math.cos(alpha); if (centerX < -0.4 || centerX > W + 0.4 || centerY < -0.4 || centerY > H + 0.4) continue; tiles.push({ x: ((centerX - tileWidth / 2) / W) * 100, y: ((centerY - thickness / 2) / H) * 100, w: (tileWidth / W) * 100, h: (thickness / H) * 100, rot: (alpha * 180) / Math.PI, scale: 1.08 }); } } return tiles; }
const FRAME_TEMPLATE = buildFrameTemplate();
const FRAME_COUNT = FRAME_TEMPLATE.length;

const defaultSleeves = [];

const state = {
  sleeves: load(STORAGE_KEY, defaultSleeves),
  favorites: load(FAVORITES_KEY, []),
  frame: load(FRAME_KEY, { cells: [] }),
  view: "homeView",
  brand: "全部品牌",
  pendingBrand: "全部品牌",
  search: "",
  imageData: "",
  frameSelectedId: null
};
function normalizeFrame(frame) { const cells = new Array(FRAME_COUNT).fill(null); const legacy = Array.isArray(frame?.cells) ? frame.cells : Array.isArray(frame?.slots) ? frame.slots : Array.isArray(frame?.items) ? frame.items.map((item) => item.sleeveId) : []; legacy.slice(0, FRAME_COUNT).forEach((id, index) => { if (id) cells[index] = id; }); return { cells }; }
state.frame = normalizeFrame(state.frame);

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
function load(key, fallback) { try { const value = JSON.parse(localStorage.getItem(key)); return value ?? fallback; } catch { return fallback; } }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function escapeHtml(value = "") { return String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char])); }
function formatDate(value) { if (!value) return ""; return value.replaceAll("-", "."); }

function artSvg(item) {
  const [a, b, c] = item.colors || ["#69a5c9", "#f1c83c", "#f3c6cf"];
  const shapes = {
    characters: `<circle cx="80" cy="62" r="25" fill="${b}"/><circle cx="119" cy="65" r="25" fill="${c}"/><path d="M55 91q36-22 90 0l-7 22H61Z" fill="${a}"/><circle cx="72" cy="62" r="4" fill="#4b3b37"/><circle cx="129" cy="64" r="4" fill="#4b3b37"/><path d="M45 109h110" stroke="#fff" stroke-width="4" opacity=".8"/>`,
    cat: `<path d="M51 45l17 8q28-20 58 0l19-9-2 35q-8 34-43 34T56 79Z" fill="${a}"/><path d="M65 69q22 15 46 0" stroke="${b}" stroke-width="7" fill="none"/><path d="M83 63h4m18 0h4" stroke="#4b3b37" stroke-width="4" stroke-linecap="round"/><path d="M78 83q10 7 20 0" stroke="#4b3b37" stroke-width="3" fill="none"/>`,
    dog: `<path d="M50 42l19 9q29-16 60 2l17-13-1 55q-35 26-91 0Z" fill="${a}"/><path d="M73 52q-7 25 15 29 30 6 28-28" fill="${c}"/><circle cx="88" cy="67" r="4" fill="#333"/><circle cx="105" cy="67" r="4" fill="#333"/><path d="M91 79q6 7 12 0" stroke="#333" stroke-width="3" fill="none"/>`,
    bear: `<path d="M60 45q-4-24 14-24 11 1 12 12 12-10 25-12 16 0 11 24 13 12 9 40-23 22-49 0-1-28 10-40Z" fill="${a}"/><circle cx="84" cy="69" r="4"/><circle cx="111" cy="69" r="4"/><ellipse cx="98" cy="80" rx="9" ry="6" fill="${b}"/>`,
    tennis: `<path d="M39 51q59-26 122 0l-12 58q-49 17-99 0Z" fill="${a}"/><circle cx="99" cy="78" r="26" fill="${b}"/><path d="M80 62q24 9 38 31M79 92q21-14 42-25" stroke="#fff" stroke-width="3" fill="none"/><path d="M60 111h76" stroke="${c}" stroke-width="6"/>`,
    city: `<path d="M43 106V70h15V55h16v51H43Zm49 0V42h18v64H92Zm30 0V62h18v44h-18Z" fill="${b}"/><path d="M34 110h132" stroke="${c}" stroke-width="9"/><circle cx="80" cy="34" r="10" fill="${a}"/>`,
    tea: `<path d="M58 42h76v41q0 30-38 30T58 83Z" fill="${a}"/><path d="M134 58h10q16 0 16 15t-16 15h-10" fill="none" stroke="${b}" stroke-width="8"/><path d="M79 36q-4-13 5-18m15 18q-4-13 5-18" stroke="${c}" stroke-width="5" fill="none" stroke-linecap="round"/>`
  };
  return `<svg class="art" viewBox="0 0 198 140" role="img" aria-label="${escapeHtml(item.name)}"><path d="M31 40Q99 22 167 40l-7 73q-61 18-122 0Z" fill="${a}" opacity=".16"/><path d="M40 42q59-18 118 0l-6 70q-55 14-106 0Z" fill="#fff" opacity=".9"/>${shapes[item.kind] || shapes.characters}<path d="M47 116q50 13 104 0" stroke="#7c7770" stroke-width="2" opacity=".35" fill="none"/></svg>`;
}

function filteredSleeves() {
  return state.sleeves.filter((item) => {
    const brandMatch = state.brand === "全部品牌" || item.brand === state.brand;
    const query = state.search.trim().toLowerCase();
    const searchMatch = !query || `${item.name} ${item.brand} ${item.enBrand}`.toLowerCase().includes(query);
    return brandMatch && searchMatch;
  });
}

function renderHome() {
  const list = filteredSleeves();
  $("#totalCount").textContent = state.sleeves.length;
  $(".home-intro h1").innerHTML = state.sleeves.length ? `把喜欢的杯套，<br /><em>好好收藏。</em>` : `从第一只杯套，<br /><em>开始收藏。</em>`;
  $("#activeFilter").hidden = state.brand === "全部品牌";
  $("#activeFilter").textContent = `当前筛选：${state.brand}  ×`;
  const groups = [...new Set(list.map((item) => item.brand))];
  if (!list.length) { $("#collectionList").innerHTML = `<div class="empty-state"><div class="empty-heart">♡</div><p>没有找到匹配的杯套</p><button class="primary-button" id="resetSearch">看看全部收藏</button></div>`; $("#resetSearch").onclick = () => { state.brand = "全部品牌"; state.search = ""; $("#searchInput").value = ""; renderHome(); }; return; }
  $("#collectionList").innerHTML = groups.map((brand) => {
    const items = list.filter((item) => item.brand === brand);
    const en = items[0]?.enBrand || "";
    return `<section class="brand-section"><div class="brand-heading"><div><h2>${escapeHtml(brand)}</h2><p>${escapeHtml(en)}</p></div><span class="count">${items.length} 件</span></div><div class="sleeve-grid">${items.map(cardHtml).join("")}</div></section>`;
  }).join("");
  $$(".sleeve-card").forEach((card) => card.addEventListener("click", (event) => { if (!event.target.closest(".favorite-toggle")) openDetail(card.dataset.id); }));
  $$(".favorite-toggle").forEach((button) => button.addEventListener("click", (event) => { event.stopPropagation(); toggleFavorite(button.dataset.id); }));
}

function visualHtml(item) { return item.image ? `<img class="art custom-art" src="${item.image}" alt="${escapeHtml(item.name)}" />` : artSvg(item); }
function cardHtml(item) { const saved = state.favorites.includes(item.id); return `<article class="sleeve-card" data-id="${escapeHtml(item.id)}"><div class="art-wrap ${item.image ? "photo-board" : ""}" style="background: ${item.image ? "#f1f0eb" : `linear-gradient(135deg, ${item.colors[0]}18, #eeefef 65%)`}">${visualHtml(item)}<button class="favorite-toggle ${saved ? "saved" : ""}" data-id="${escapeHtml(item.id)}" aria-label="${saved ? "取消收藏" : "收藏"}">${saved ? "♥" : "♡"}</button></div><div class="card-body"><h3>${escapeHtml(item.name)}</h3><div class="card-meta"><span class="tag ${item.tag === "常规款" ? "normal" : ""}">${escapeHtml(item.tag)}</span><span>${escapeHtml(item.date)}</span></div></div></article>`; }

function renderFavorites() { const items = state.sleeves.filter((item) => state.favorites.includes(item.id)); $("#favoriteCount").textContent = items.length; $("#favoritesList").innerHTML = items.length ? `<div class="sleeve-grid">${items.map(cardHtml).join("")}</div>` : `<div class="empty-state"><div class="empty-heart">♡</div><p>还没有收藏的杯套</p><button class="primary-button" id="goHomeButton">去首页逛逛</button></div>`; $$("#favoritesList .sleeve-card").forEach((card) => card.addEventListener("click", (event) => { if (!event.target.closest(".favorite-toggle")) openDetail(card.dataset.id); })); $$("#favoritesList .favorite-toggle").forEach((button) => button.addEventListener("click", (event) => { event.stopPropagation(); toggleFavorite(button.dataset.id); })); $("#goHomeButton")?.addEventListener("click", () => switchView("homeView")); }

function saveFrame() { try { save(FRAME_KEY, state.frame); } catch { showToast("相框布局保存失败"); } }
function frameSleeves() { return state.sleeves.filter((item) => item.image); }
function renderFrameTray() { const list = frameSleeves(); $("#frameTray").innerHTML = list.length ? list.map((item) => `<button class="tray-item ${state.frameSelectedId === item.id ? "selected" : ""}" data-id="${escapeHtml(item.id)}" aria-label="选择杯套：${escapeHtml(item.name)}"><img src="${item.image}" alt="${escapeHtml(item.name)}" /></button>`).join("") : `<p class="tray-empty">还没有上传的杯套，先去上传一只吧</p>`; $$("#frameTray .tray-item").forEach((button) => button.addEventListener("click", () => selectFrameSleeve(button.dataset.id))); }
function selectFrameSleeve(sleeveId) { const sleeve = state.sleeves.find((entry) => entry.id === sleeveId); if (!sleeve) return; state.frameSelectedId = state.frameSelectedId === sleeveId ? null : sleeveId; renderFrame(); if (state.frameSelectedId) showToast(`已选中「${sleeve.name}」，点相框位置放入`); }
function renderFrame() { renderFrameTray(); const stage = $("#frameStage"); $$("#frameStage .frame-slot").forEach((slot) => slot.remove()); const cells = state.frame.cells; const filled = cells.filter(Boolean).length; const list = frameSleeves(); $("#frameHint").hidden = filled > 0 || Boolean(state.frameSelectedId); $("#frameHint").textContent = list.length ? "点下方杯套选中，再点相框里的位置放入" : "先去上传一只杯套，才能填进相框"; stage.classList.toggle("placing", Boolean(state.frameSelectedId)); FRAME_TEMPLATE.forEach((slot, index) => { const sleeveId = cells[index]; const sleeve = sleeveId ? state.sleeves.find((entry) => entry.id === sleeveId) : null; const button = document.createElement("button"); button.type = "button"; button.className = `frame-slot ${sleeve ? "filled" : "empty"}`; button.dataset.index = index; button.style.cssText = `left:${slot.x}%;top:${slot.y}%;width:${slot.w}%;height:${slot.h}%;transform:rotate(${slot.rot}deg) scale(${slot.scale});z-index:${index}`; if (sleeve) button.innerHTML = `<img src="${sleeve.image}" alt="${escapeHtml(sleeve.name)}" />`; button.addEventListener("click", () => tapFrameSlot(index)); stage.appendChild(button); }); }
function tapFrameSlot(index) { const cells = state.frame.cells; if (state.frameSelectedId) { cells[index] = state.frameSelectedId; saveFrame(); renderFrame(); showToast("已放入相框"); return; } if (cells[index]) { cells[index] = null; saveFrame(); renderFrame(); showToast("已移除这个位置的杯套"); } else { showToast("先点下方杯套选中，再点这里放入"); } }
function clearFrame() { if (!state.frame.cells.some(Boolean)) { showToast("相框还是空的"); return; } if (!confirm("确认清空相框吗？\n\n所有摆放都会被移除，无法撤销。")) return; state.frame.cells = new Array(FRAME_COUNT).fill(null); state.frameSelectedId = null; saveFrame(); renderFrame(); showToast("已清空相框"); }
function loadImage(src) { return new Promise((resolve) => { if (!src) { resolve(null); return; } const image = new Image(); image.onload = () => resolve(image); image.onerror = () => resolve(null); image.src = src; }); }
function drawCover(context, image, x, y, width, height) { const imageRatio = image.width / image.height; const targetRatio = width / height; let sx = 0; let sy = 0; let sw = image.width; let sh = image.height; if (imageRatio > targetRatio) { sw = image.height * targetRatio; sx = (image.width - sw) / 2; } else { sh = image.width / targetRatio; sy = (image.height - sh) / 2; } context.drawImage(image, sx, sy, sw, sh, x, y, width, height); }
async function exportFrame() { const entries = state.frame.cells.map((id, index) => ({ id, index })).filter((entry) => entry.id); if (!entries.length) { showToast("相框还是空的"); return; } const width = 1600; const height = 1200; const canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height; const context = canvas.getContext("2d"); context.fillStyle = "#fffefa"; context.fillRect(0, 0, width, height); const cache = new Map(); for (const entry of entries) { if (cache.has(entry.id)) continue; const sleeve = state.sleeves.find((item) => item.id === entry.id); cache.set(entry.id, await loadImage(sleeve?.image)); } for (const entry of entries) { const image = cache.get(entry.id); if (!image) continue; const slot = FRAME_TEMPLATE[entry.index]; const cellWidth = (slot.w / 100) * width; const cellHeight = (slot.h / 100) * height; const centerX = (slot.x / 100) * width + cellWidth / 2; const centerY = (slot.y / 100) * height + cellHeight / 2; const scale = slot.scale; context.save(); context.translate(centerX, centerY); context.rotate((slot.rot * Math.PI) / 180); drawCover(context, image, (-cellWidth * scale) / 2, (-cellHeight * scale) / 2, cellWidth * scale, cellHeight * scale); context.restore(); } canvas.toBlob((blob) => { if (!blob) { showToast("导出失败，请重试"); return; } const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `杯套相框-${new Date().toISOString().slice(0, 10)}.png`; link.click(); URL.revokeObjectURL(url); showToast("相框图片已导出"); }, "image/png"); }

function switchView(viewId) { state.view = viewId; $$(".view").forEach((view) => view.classList.toggle("active", view.id === viewId)); $$(".nav-item").forEach((item) => item.classList.toggle("active", item.dataset.view === viewId)); if (viewId === "homeView") renderHome(); if (viewId === "favoritesView") renderFavorites(); if (viewId === "frameView") renderFrame(); window.scrollTo({ top: 0, behavior: "smooth" }); }
function toggleFavorite(id) { const index = state.favorites.indexOf(id); if (index >= 0) { state.favorites.splice(index, 1); showToast("已取消收藏"); } else { state.favorites.push(id); showToast("已加入收藏"); } save(FAVORITES_KEY, state.favorites); renderHome(); if (state.view === "favoritesView") renderFavorites(); }
function openDetail(id) { const item = state.sleeves.find((entry) => entry.id === id); if (!item) return; const deleteButton = item.custom ? `<button class="detail-delete" id="detailDelete">删除这只杯套</button>` : ""; $("#detailContent").innerHTML = `<div class="detail-art ${item.image ? "photo-board" : ""}" style="background:${item.image ? "#f1f0eb" : `linear-gradient(135deg, ${item.colors[0]}25, #eeefef)`}">${visualHtml(item)}</div><div class="detail-body"><span class="tag ${item.tag === "常规款" ? "normal" : ""}">${escapeHtml(item.tag)}</span><h2>${escapeHtml(item.name)}</h2><span class="detail-brand">${escapeHtml(item.brand)} · ${escapeHtml(item.enBrand || "")}</span><p>${escapeHtml(item.story || "这枚杯套还没有故事，等你来补充。")}</p><div class="detail-date">发行时间 · ${escapeHtml(item.date)}</div>${deleteButton}</div>`; $("#detailModal").hidden = false; $("#detailDelete")?.addEventListener("click", () => deleteSleeve(item.id)); }
function deleteSleeve(id) { const item = state.sleeves.find((entry) => entry.id === id); if (!item) return; if (!confirm(`确认删除「${item.name}」吗？\n\n删除后这只杯套将从收藏馆和收藏列表中移除，无法撤销。`)) return; state.sleeves = state.sleeves.filter((entry) => entry.id !== id); state.favorites = state.favorites.filter((favoriteId) => favoriteId !== id); save(STORAGE_KEY, state.sleeves); save(FAVORITES_KEY, state.favorites); state.frame.cells = state.frame.cells.map((cellId) => (cellId === id ? null : cellId)); if (state.frameSelectedId === id) state.frameSelectedId = null; saveFrame(); closeModal($("#detailModal")); renderHome(); if (state.view === "favoritesView") renderFavorites(); if (state.view === "frameView") renderFrame(); showToast("已删除这只杯套"); }
function closeModal(element) { element.hidden = true; }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("show"); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove("show"), 2600); }
function restoreBackup(file) { if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const backup = JSON.parse(reader.result); if (!backup || !Array.isArray(backup.sleeves) || !Array.isArray(backup.favorites)) throw new Error("invalid"); if (!confirm(`确认用这份备份覆盖当前本地数据吗？\n\n备份包含 ${backup.sleeves.length} 个杯套、${backup.favorites.length} 个收藏。\n当前本地数据会被替换，无法撤销。`)) return; state.sleeves = backup.sleeves; state.favorites = backup.favorites.filter((id) => state.sleeves.some((item) => item.id === id)); save(STORAGE_KEY, state.sleeves); save(FAVORITES_KEY, state.favorites); state.brand = "全部品牌"; state.search = ""; $("#searchInput").value = ""; state.frame.cells = state.frame.cells.map((cellId) => (cellId && state.sleeves.some((item) => item.id === cellId) ? cellId : null)); saveFrame(); renderHome(); renderFavorites(); renderFrame(); showToast("恢复成功，已用备份替换本地数据"); } catch { showToast("不是有效的收藏馆备份文件"); } finally { $("#restoreInput").value = ""; } }; reader.readAsText(file, "UTF-8"); }

function openBrandModal() { state.pendingBrand = state.brand; $("#brandOptions").innerHTML = ["全部品牌", ...new Set(state.sleeves.map((item) => item.brand))].map((brand) => `<button class="brand-option ${state.pendingBrand === brand ? "selected" : ""}" data-brand="${escapeHtml(brand)}">${escapeHtml(brand)}</button>`).join(""); $$(".brand-option").forEach((button) => button.addEventListener("click", () => { state.pendingBrand = button.dataset.brand; $$(".brand-option").forEach((item) => item.classList.toggle("selected", item === button)); })); $("#brandModal").hidden = false; }

function compressImage(file, maxSize = 1280, quality = .82) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const scale = Math.min(1, maxSize / Math.max(image.width, image.height)); const width = Math.max(1, Math.round(image.width * scale)); const height = Math.max(1, Math.round(image.height * scale)); const canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height; const context = canvas.getContext("2d"); context.fillStyle = "#ffffff"; context.fillRect(0, 0, width, height); context.drawImage(image, 0, 0, width, height); try { resolve(canvas.toDataURL("image/jpeg", quality)); } catch { reject(new Error("compress failed")); } }; image.onerror = () => reject(new Error("decode failed")); image.src = reader.result; }; reader.onerror = () => reject(new Error("read failed")); reader.readAsDataURL(file); }); }

function submitUpload(event) { event.preventDefault(); if (!state.imageData) { showToast("请先选择一张杯套图片"); return; } const sleeve = { id: `custom-${Date.now()}`, brand: $("#brandInput").value, enBrand: "My Archive", name: $("#sleeveName").value.trim(), date: formatDate($("#dateInput").value), tag: $("#tagInput").value, story: $("#storyInput").value.trim() || "这是一枚值得留下来的杯套。", colors: ["#b9c8d9", "#e5b66c", "#f1d9cf"], kind: "characters", custom: true, image: state.imageData }; const next = [sleeve, ...state.sleeves]; try { save(STORAGE_KEY, next); } catch { showToast("保存失败：图片太大，请换一张更小的图片"); return; } state.sleeves = next; showToast("上传成功，已加入你的收藏馆"); event.target.reset(); $("#imagePreview").hidden = true; $("#imagePreview").removeAttribute("src"); $("#imagePicker").classList.remove("has-image"); state.imageData = ""; switchView("homeView"); }

$("#searchInput").addEventListener("input", (event) => { state.search = event.target.value; renderHome(); }); $("#restoreButton").addEventListener("click", () => $("#restoreInput").click()); $("#restoreInput").addEventListener("change", (event) => restoreBackup(event.target.files?.[0])); $("#brandFilterButton").addEventListener("click", openBrandModal); $("#cancelBrand").addEventListener("click", () => closeModal($("#brandModal"))); $("#confirmBrand").addEventListener("click", () => { state.brand = state.pendingBrand; closeModal($("#brandModal")); renderHome(); }); $("#activeFilter").addEventListener("click", () => { state.brand = "全部品牌"; renderHome(); }); $("#closeDetail").addEventListener("click", () => closeModal($("#detailModal"))); $("#detailModal").addEventListener("click", (event) => { if (event.target.id === "detailModal") closeModal(event.target); }); $("#uploadForm").addEventListener("submit", submitUpload); $("#dateInput").value = new Date().toISOString().slice(0, 10); $("#imageInput").addEventListener("change", (event) => { const file = event.target.files?.[0]; if (!file) return; const showPreview = (dataUrl) => { state.imageData = dataUrl; $("#imagePreview").src = dataUrl; $("#imagePreview").hidden = false; $("#imagePicker").classList.add("has-image"); }; compressImage(file).then(showPreview).catch(() => { const reader = new FileReader(); reader.onload = () => showPreview(reader.result); reader.onerror = () => showToast("图片读取失败，请换一张试试"); reader.readAsDataURL(file); }); }); $("#clearFavorites").addEventListener("click", () => { if (!state.favorites.length) { showToast("还没有收藏内容"); return; } state.favorites = []; save(FAVORITES_KEY, state.favorites); renderFavorites(); showToast("已清空收藏"); }); $("#backupButton").addEventListener("click", () => { const blob = new Blob([JSON.stringify({ sleeves: state.sleeves, favorites: state.favorites }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `杯套收藏馆备份-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); showToast("备份文件已下载"); }); $("#feedbackButton").addEventListener("click", () => showToast("自用版暂未接入反馈服务")); $("#frameExport").addEventListener("click", exportFrame); $("#frameClear").addEventListener("click", clearFrame); $("#menuButton").addEventListener("click", () => showToast("这是一个纯前端自用版，数据只保存在本机")); $$(".nav-item").forEach((item) => item.addEventListener("click", () => switchView(item.dataset.view))); setInterval(() => { $("#statusTime").textContent = new Date().toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" }); }, 30000);
renderHome();
